#!/usr/bin/env python3
"""Regenerate the SBOM tables in sbom.md: installed packages + external artifacts.

Package table sourced from `pyproject.toml` + `uv.lock` (via `uv run --all-groups
pip-licenses`, which reports on whatever is actually installed for every dependency
group) rather than parsing either file directly, since neither carries
license/homepage/summary metadata on its own. The table is restricted to packages
`pyproject.toml` actually declares (project.dependencies + every dependency-group) --
pip-licenses also reports the full transitive closure from uv.lock, which is mostly
indirect dependencies-of-dependencies never referenced by this project directly.

External-artifacts table (model checkpoints, datasets, etc. downloaded at runtime from
somewhere other than a pip package -- e.g. `huggingface_hub.hf_hub_download(...)` calls
in a notebook) isn't installed metadata `pip-licenses` can see, so it's sourced from
`external_artifacts.json` in this directory instead -- a small hand-maintained manifest,
since license info for an arbitrary external repo generally needs a human (or agent) to
actually go look, the same way this file's own `braindecode/plot_bcic_iv_2a_moabb_trial`
entry was researched. `scan_hf_hub_download_repo_ids()` finds `hf_hub_download(...)`
call sites across the repo and cross-checks their `repo_id`s against the manifest,
warning (not failing) on anything referenced in code but missing from the manifest --
see `find_undocumented_artifacts()`.
"""

import json
import re
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
PYPROJECT_PATH = ROOT / "pyproject.toml"
SBOM_PATH = ROOT / "sbom.md"
EXTERNAL_ARTIFACTS_PATH = Path(__file__).resolve().parent / "external_artifacts.json"
START = "<!-- SBOM:START (auto-generated by .claude/skills/generate-sbom/generate_sbom.py -- do not edit by hand) -->"
END = "<!-- SBOM:END -->"
EXTERNAL_START = "<!-- SBOM-EXTERNAL:START (auto-generated from .claude/skills/generate-sbom/external_artifacts.json -- do not edit by hand) -->"
EXTERNAL_END = "<!-- SBOM-EXTERNAL:END -->"
MAX_CELL_LEN = 300

HEADER = """# SBOM (Software Bill of Materials)

`pyproject.toml`에 직접 선언된 의존성(`project.dependencies` + 모든 dependency group)을 알파벳순으로 정리한 표입니다.
`.claude/skills/generate-sbom/generate_sbom.py`가 `pip-licenses`로 설치된 패키지 메타데이터를 읽어 자동 생성하며,
`pyproject.toml`이 수정될 때마다 후크(`.claude/settings.json`)가 이 표를 갱신합니다. 표 구간을 손으로 편집하지 마세요.

pip 패키지가 아니라 실행 중에 외부에서 내려받는 아티팩트(모델 체크포인트 등, 예: `huggingface_hub.hf_hub_download(...)`)는
아래 별도 표에 나열됩니다 — `pip-licenses`가 볼 수 없는 대상이라 `external_artifacts.json`을 손으로(또는 에이전트가) 채워야
합니다. 코드에서 `hf_hub_download(...)` 호출을 새로 추가하면 훅이 이 표를 다시 생성하면서, 그 `repo_id`가
`external_artifacts.json`에 없으면 경고를 남깁니다.
"""

_NAME_RE = re.compile(r"^\s*([A-Za-z0-9][A-Za-z0-9._-]*)")


def normalize(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def requirement_name(requirement: str) -> str | None:
    match = _NAME_RE.match(requirement)
    return normalize(match.group(1)) if match else None


def direct_dependency_names() -> set[str]:
    data = tomllib.loads(PYPROJECT_PATH.read_text())
    names = set()
    for req in data.get("project", {}).get("dependencies", []):
        name = requirement_name(req)
        if name:
            names.add(name)
    for entries in data.get("dependency-groups", {}).values():
        for entry in entries:
            if isinstance(entry, str):
                name = requirement_name(entry)
                if name:
                    names.add(name)
    return names


def get_packages():
    result = subprocess.run(
        [
            "uv",
            "run",
            "--all-groups",
            "pip-licenses",
            "--with-system",
            "--with-urls",
            "--with-description",
            "--format=json",
        ],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return json.loads(result.stdout)


def clean_cell(text: str | None, fallback: str = "N/A") -> str:
    if not text:
        return fallback
    text = " ".join(text.split())  # collapses newlines/tabs/repeated spaces alike
    text = text.replace("|", "\\|")
    if len(text) > MAX_CELL_LEN:
        text = text[: MAX_CELL_LEN - 1].rstrip() + "…"
    return text or fallback


def build_table(packages):
    wanted = direct_dependency_names()
    packages = [p for p in packages if normalize(p["Name"]) in wanted]
    packages.sort(key=lambda p: p["Name"].lower())
    lines = [
        "| 번호 | 라이브러리명 | 버전 | 라이선스 | 공식 저장소 URL | 사용 목적 및 주요 기능 |",
        "|---|---|---|---|---|---|",
    ]
    for i, pkg in enumerate(packages, 1):
        name = pkg["Name"]
        version = clean_cell(pkg.get("Version"))
        license_ = clean_cell(pkg.get("License"))
        url = clean_cell(pkg.get("URL"))
        desc = clean_cell(pkg.get("Description"))
        lines.append(f"| {i} | {name} | {version} | {license_} | {url} | {desc} |")

    missing = sorted(wanted - {normalize(p["Name"]) for p in packages})
    if missing:
        print(
            f"sbom.md: WARNING no installed package matched: {', '.join(missing)}",
            file=sys.stderr,
        )

    return "\n".join(lines), len(packages)


_HF_HUB_DOWNLOAD_RE = re.compile(r"hf_hub_download\s*\(")
_REPO_ID_LITERAL_RE = re.compile(r"""["']([\w][\w.-]*/[\w][\w.-]*)["']""")
_SCAN_DIRS = ("src", "examples", "demos", "tests")
_SCAN_SUFFIXES = (".py", ".ipynb")


def _iter_source_texts(path: Path):
    """Yield the plain-Python text to scan from `path` -- cell sources for a notebook
    (so scanning never trips over JSON string-escaping), the raw file otherwise."""
    if path.suffix == ".ipynb":
        try:
            nb = json.loads(path.read_text())
        except (json.JSONDecodeError, UnicodeDecodeError):
            return
        for cell in nb.get("cells", []):
            if cell.get("cell_type") == "code":
                yield "".join(cell.get("source", []))
    else:
        try:
            yield path.read_text()
        except UnicodeDecodeError:
            return


def scan_hf_hub_download_repo_ids() -> set[str]:
    """`repo_id`s of every `hf_hub_download(...)` call site under `_SCAN_DIRS`.

    Handles both the literal-argument form (`hf_hub_download("org/name", ...)`) and the
    much more common variable form (`repo_id = "org/name"` a few lines above
    `hf_hub_download(repo_id, ...)`) by taking every `"org/name"`-shaped string literal
    in a source that contains at least one `hf_hub_download(` call -- not a precise
    parse, but this is a nudge to keep the manifest honest, not a security gate.
    """
    found = set()
    for scan_dir in _SCAN_DIRS:
        base = ROOT / scan_dir
        if not base.exists():
            continue
        for path in base.rglob("*"):
            if path.suffix not in _SCAN_SUFFIXES or not path.is_file():
                continue
            for text in _iter_source_texts(path):
                if not _HF_HUB_DOWNLOAD_RE.search(text):
                    continue
                found.update(_REPO_ID_LITERAL_RE.findall(text))
    return found


def load_external_artifacts() -> list[dict]:
    if not EXTERNAL_ARTIFACTS_PATH.exists():
        return []
    return json.loads(EXTERNAL_ARTIFACTS_PATH.read_text())


def find_undocumented_artifacts(artifacts: list[dict]) -> set[str]:
    documented = {a["repo_id"] for a in artifacts}
    return scan_hf_hub_download_repo_ids() - documented


def build_external_artifacts_table(artifacts: list[dict]) -> str:
    lines = [
        "| 번호 | 아티팩트 | 종류 | 버전 | 라이선스 | URL | 사용처 | 용도 |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for i, a in enumerate(sorted(artifacts, key=lambda a: a["repo_id"]), 1):
        repo_id = clean_cell(a.get("repo_id"))
        type_ = clean_cell(a.get("type"))
        version = clean_cell(a.get("version"))
        license_ = clean_cell(a.get("license"))
        note = a.get("license_note")
        if note:
            license_ = f"{license_} ({clean_cell(note)})"
        url = clean_cell(a.get("url"))
        used_in = clean_cell(a.get("used_in"))
        purpose = clean_cell(a.get("purpose"))
        lines.append(
            f"| {i} | {repo_id} | {type_} | {version} | {license_} | {url} | {used_in} | {purpose} |"
        )
    if not artifacts:
        lines.append("| - | (none yet) | | | | | | |")
    return "\n".join(lines)


def render(content: str, blocks: list[tuple[str, str, str]]) -> str:
    """Replace/insert each `(start_marker, end_marker, block)` in `content`, in order."""
    for start, end, block in blocks:
        if start in content and end in content:
            pre, rest = content.split(start, 1)
            _, post = rest.split(end, 1)
            content = f"{pre.rstrip()}\n\n{block}\n{post.lstrip()}".rstrip() + "\n"
        elif content.strip():
            content = f"{content.rstrip()}\n\n{block}\n"
        else:
            content = f"{HEADER}\n{block}\n"
    return content


def main():
    packages = get_packages()
    table, count = build_table(packages)
    package_block = f"{START}\n\n{table}\n\n{END}"

    artifacts = load_external_artifacts()
    external_table = build_external_artifacts_table(artifacts)
    external_block = f"{EXTERNAL_START}\n\n{external_table}\n\n{EXTERNAL_END}"

    existing = SBOM_PATH.read_text() if SBOM_PATH.exists() else ""
    SBOM_PATH.write_text(
        render(
            existing,
            [
                (START, END, package_block),
                (EXTERNAL_START, EXTERNAL_END, external_block),
            ],
        )
    )
    print(
        f"sbom.md: wrote {count} packages, {len(artifacts)} external artifacts",
        file=sys.stderr,
    )

    undocumented = find_undocumented_artifacts(artifacts)
    if undocumented:
        print(
            "sbom.md: WARNING hf_hub_download() references not in "
            f"external_artifacts.json: {', '.join(sorted(undocumented))}",
            file=sys.stderr,
        )


if __name__ == "__main__":
    main()
